### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by jenius**
What started as a series of small bugfixes ended up being a large refactor and reorganization. Everything now is much cleaner and easier to deal with, chipping away at better and more thorough tests and closing out all the tickets in this repo :grinning:

### CODE REVIEW

**Comment by jenius** [comment]
**Update:** We're most of the way there. Library is ready and working well, tested with a live project and it's already closed out a couple bugs. I want to make sure the test suite is *very* thorough. Scaffolded out a good set of tests that covers every possible edge I can think of. Will be working through implementing these tests until they are all ready and we're at 100% coverage, then ship a minor version bump. Whoo!

If anyone has any ideas for other features they want, now is the time to pipe in :grinning:

**Comment by kylemac** [comment]
some kind of caching is my feature request...

**Comment by jenius** [comment]
Good call @kylemac -- I'll look into adding a cache system after this piece is ready. You're just talking about cacheing between saves during watch right? Or between different watches?

A lot of people have been requesting reload and data push as well when a json file source is saved, but that's going to be a bit more of a challenge.

**Comment by kylemac** [comment]
yeah, between watches. my initial idea would be to expose a `cache: true` option and if true it compiles and then writes your data to a tmp json file and then uses that file (instead of the network request) for subsequent reqs. 

i don't have a use-case for between watches but if I did have that problem - I'd just make my own file to read from and provision production to use the network'd endpoint

**Comment by jenius** [comment]
So while you are in watch mode it already caches into memory, as the `setup` function runs once and saves the data into variables. As such I think we can skip this for now unless there's a good use case for cacheing between watches!

**Comment by kylemac** [comment]
nope, that works for me

**Pull request merged**
