### PR TITLE
add new argument to queue url requests using cwait

### PR DESCRIPTION
**Pull request by benadamstyles**
I just had to make this as we are using roots-records with a BIG site and the multiple concurrent requests are bringing down our server. Rather than just ploughing more RAM into the server, simply queueing all requests to limit concurrency fixes this for us. The API I've chosen (simply passing a concurrency limit `number` into `records()`) is not the greatest but I just wondered if this would be something you might consider merging. Happy to do a bit more work on it if needed.

### CODE REVIEW

**Comment by jescalan** [comment]
Hey there, thanks for diving in and making this PR! Would be happy to accept functionality like this, I'd just make a couple small changes to how it's implemented:
- Use [when.guard](https://github.com/cujojs/when/blob/master/docs/api.md#limiting-concurrency) instead of adding an extra dependency
- Accept the option through a `limitConcurrency` key on the options object, rather than passing a second argument.

Thoughts?

**Comment by benadamstyles** [comment]
How's this? `when/guard` isn't as easy to grok as `cwait` but I think I've got it right. I'd like to add a test to prove it is limiting the concurrency but can't for the life of me think how to do it reliably.

**Comment by jescalan** [comment]
Looks good! Tests are failing on travis due to a linting error though

**Comment by benadamstyles** [comment]
Coffeescript is not intuitive to me, I really don't know where I can break some lines.

Any ideas about the concurrency test? I guess I could just test that a lower number results in a longer delay...

**Comment by jescalan** [comment]
Yeah, that's a tough one, I think the time comparison is the best approach!

**Comment by benadamstyles** [comment]
Added documentation – no idea why the tests have failed?

**Pull request closed without merging**
