### PR TITLE
Single views

### LINKED ISSUE #6: [FEATURE REQUEST] Add single view compiling support to roots-records
I would like to serve Roots JSON API data from our custom CMS and be able to create the pages from the pages generated from our API.

This feature would allow me to utilize Roots sort of how you utilize Roots-Wordpress or Roots-Contentful, and allow me to continue to use our CMS for managing the content. 

Thank you so much for your time!!!

### PR DESCRIPTION
**Pull request by joshrowley**
Hey, this adds support for creating single page views from your records as discussed in #6. Let me know what you guys think / where it can be improved.

Closes #6

### CODE REVIEW

**Comment by nporteschaikin** [comment]
So the `path` key is already in use ([here](https://github.com/carrot/roots-records/blob/44aba46fb10eb9eaace29dbd7111f34e94769b1e/lib/index.coffee#L114)).  However, I prefer your approach to returning a specific key-path (using a function).  Any chance we could implement that in a separate PR and rebase this on top of it?  I can write it, too, if you prefer.  

This is a must-have feature.  Great discovery and great work.  :+1:

**Comment by joshrowley** [comment]
Cool, yeah I can submit a PR w that change today, I figured having it be a function makes it super flexible in case you want to manipulate the data in any way before passing it into your templates.

**Comment by nporteschaikin** [comment]
@joshrowley Agreed. :+1:

**Comment by joshrowley** [comment]
Should it still be called `path`, is there a better name for it?

**Comment by nporteschaikin** [comment]
@joshrowley Good question.  Maybe `data`?

**Comment by joshrowley** [comment]
I believe the `data` key is used right now for directly passing an object in

**Comment by nporteschaikin** [comment]
@joshrowley Let's go with `collection`.

**Comment by joshrowley** [comment]
@nporteschaikin `collection` is specifically for giving the single page views a collection to iterate over, whereas this is a more general `hook` (that's what I ended up naming it) that let's you manipulate the data before it's set to `records.<key>`. PR incoming, lmk what you think.

**Comment by joshrowley** [comment]
@nporteschaikin rebased, ready for review

**Comment by nporteschaikin** [comment]
@joshrowley love it.

**Pull request merged**
